### ISSUE TITLE
The Snapshots end point is incomplete

### ISSUE THREAD

**Issue by erickalfaro** [polygon-io/client-python#507] opened 2023-08-31 02:54 UTC
The Snapshots end point is for all assets does not return the n variable. 

Endpoint: 
https://api.polygon.io/v2/snapshot/locale/us/markets/stocks/tickers?apiKey=

Documentation: 
https://polygon.io/docs/stocks/get_v2_snapshot_locale_us_markets_stocks_tickers

![image](https://github.com/polygon-io/client-python/assets/8908857/177f2c94-ec2f-4f93-bfa4-ae977cc699c5)

**Comment by justinpolygon** [comment] 2023-09-04 16:54
Hi @erickalfaro, I'm running v1.12.4 and see snapshot min.transactions which is mapped to `n`. The market is closed for the holiday today. Do you mind updating the client-python library via `pip install -U polygon-api-client` and testing again?

If you run https://github.com/polygon-io/client-python/blob/master/examples/rest/stocks-snapshots_all.py you should see something like `min=MinuteSnapshot(accumulated_volume=0, open=0, high=0, low=0, close=0, volume=0, vwap=0, otc=None, timestamp=0, transactions=0)` and `transactions` is what you're looking for. Although, if you run it when the market's closed you're not going to see anything.

Let me know what you see.

**Comment by justinpolygon** [comment] 2023-09-05 15:38
Hi @erickalfaro, now that the markets are open I re-ran that example and have some real data to use. If I run that example script above you'll see something like this:

```
TickerSnapshot(day=Agg(open=188.28, high=189.61, low=187.61, close=189.29, volume=20840397.0, vwap=188.5147, timestamp=None, transactions=None, otc=None), last_quote=LastQuote(ticker=None, trf_timestamp=None, sequence_number=None, sip_timestamp=1693927693352242846, participant_timestamp=None, ask_price=189.27, ask_size=6, ask_exchange=None, conditions=None, indicators=None, bid_price=189.26, bid_size=2, bid_exchange=None, tape=None), last_trade=LastTrade(ticker=None, trf_timestamp=None, sequence_number=None, sip_timestamp=1693927693280509336, participant_timestamp=None, conditions=None, correction=None, id='7536', price=189.265, trf_id=None, size=100, exchange=21, tape=None), min=MinuteSnapshot(accumulated_volume=20840194.0, open=189.2354, high=189.31, low=189.2001, close=189.29, volume=53964, vwap=189.2503, otc=None, timestamp=1693927620000, transactions=668), prev_day=Agg(open=189.485, high=189.92, low=188.28, close=189.46, volume=45393903.0, vwap=189.0424, timestamp=None, transactions=None, otc=None), ticker='AAPL', todays_change=-0.1950000000000216, todays_change_percent=-0.10292410007390561, updated=1693927693280509336)
```

Within the `MinuteSnapshot` you'll see `transactions` and that's what you're looking for. So, if you update the client via `pip install -U polygon-api-client` you'll see it.

**Comment by justinpolygon** [comment] 2023-09-05 19:38
Hey, I'm going to close this as not a bug since I cannot reproduce it. I suspect it's just an outdated client library but if you still have the same problem after updating please comment on this issue. Thank you.

**Closed by justinpolygon** 2023-09-05 19:38 UTC
Labels: bug
